services:
  db:
    image: postgres:18
    container_name: org_catalog_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: org_catalog_api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://catalog:catalog@db:5432/catalog
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    command: >
      sh -c "
      uv run alembic -c src/infra/alembic.ini upgrade head &&
      uv run uvicorn api:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  postgres_data: